Repository iOS-PPAK/Hygrometer_GeekCode_WhiteHyun, pull requests merged in 2022-07, with the labels that each got.

#1 MainView 기본 UI 설정
  HygrometerApp/Sources/ViewControllers/MainViewController.swift
Labels: enhancement

#3 CityViewController에 필요한 프로퍼티 추가
  HygrometerApp/Sources/ViewControllers/CityViewController.swift
Labels: enhancement

#2 Feat: addViewController TableView 구현
  .gitignore
  HygrometerApp.xcodeproj/project.pbxproj
  HygrometerApp.xcodeproj/xcshareddata/xcschemes/HygrometerApp.xcscheme
  HygrometerApp/Resources/Extentions.swift
  HygrometerApp/Resources/Network/API.swift
  HygrometerApp/Sources/GpsModel.swift
  HygrometerApp/Sources/GpsParamModel.swift
  HygrometerApp/Sources/SceneDelegate.swift
  HygrometerApp/Sources/ViewControllers/AddViewController.swift
  HygrometerApp/Sources/ViewControllers/TableViewCells/CityListTableViewCell.swift
  HygrometerApp/Sources/ViewControllers/TableViewCells/CityListTableViewCell.xib
  HygrometerApp/Sources/ViewControllers/TableViewCells/WeatherListTableViewCell.swift
  HygrometerApp/Sources/ViewControllers/TableViewCells/WeatherListTableViewCell.xib
  HygrometerApp/Sources/WeatherModel.swift
  HygrometerApp/Sources/didSaveWeatherModel.swift
Labels: enhancement

#5 API Model 수정
  HygrometerApp.xcodeproj/project.pbxproj
  HygrometerApp/Sources/GpsModel.swift
  HygrometerApp/Sources/GpsParamModel.swift
  HygrometerApp/Sources/Models/GpsRequest.swift
  HygrometerApp/Sources/Models/GpsResponse.swift
  HygrometerApp/Sources/Models/WeatherRequest.swift
  HygrometerApp/Sources/Models/WeatherResponse.swift
  HygrometerApp/Sources/Models/didSaveWeatherModel.swift
  HygrometerApp/Sources/WeatherModel.swift
Labels: enhancement

#7 Feat: searchBar 동작 연결
  HygrometerApp/Sources/ViewControllers/AddViewController.swift
  HygrometerApp/Sources/ViewControllers/TableViewCells/CityListTableViewCell.swift
Labels: enhancement

#9 ViewController Move-Flow
  HygrometerApp/Sources/SceneDelegate.swift
  HygrometerApp/Sources/ViewControllers/MainViewController.swift
Labels: enhancement

#10 리팩토링 진행
  HygrometerApp.xcodeproj/project.pbxproj
  HygrometerApp/Resources/Network/API.swift
  HygrometerApp/Sources/Extensions/ShadowSet.swift
  HygrometerApp/Sources/Extensions/UIColor.swift
  HygrometerApp/Sources/Extensions/UIView.swift
  HygrometerApp/Sources/Models/UserData.swift
  HygrometerApp/Sources/Models/WeatherRequest.swift
  HygrometerApp/Sources/Models/didSaveWeatherModel.swift
  HygrometerApp/Sources/ViewControllers/AddViewController.swift
  HygrometerApp/Sources/ViewControllers/TableViewCells/CityListTableViewCell.swift
  HygrometerApp/Sources/ViewControllers/TableViewCells/CityListTableViewCell.xib
  HygrometerApp/Sources/ViewControllers/TableViewCells/WeatherListTableViewCell.swift
  HygrometerApp/Sources/ViewControllers/TableViewCells/WeatherListTableViewCell.xib
Labels: Refactoring

#11 City ViewController 스와이프 기능 추가
  HygrometerApp/Sources/ViewControllers/MainViewController.swift
Labels: enhancement

#12 City ViewController 스와이프 기능 추가
  HygrometerApp/Sources/ViewControllers/MainViewController.swift
Labels: enhancement

#13 feat: AddViewController에 KeyboardMonitor 추가
  HygrometerApp.xcodeproj/project.pbxproj
  HygrometerApp/Sources/ViewControllers/AddViewController.swift
  HygrometerApp/Sources/ViewControllers/KeyboardMonitor.swift
Labels: enhancement

#14 HotFix - request model 수정
  HygrometerApp/Sources/Models/WeatherRequest.swift
Labels: bug

#15 API 연동 후 각 도시 별 습도 업데이트
  HygrometerApp.xcodeproj/project.pbxproj
  HygrometerApp/Info.plist
  HygrometerApp/Resources/Network/API.swift
  HygrometerApp/Sources/Managers/LocationManager.swift
  HygrometerApp/Sources/Models/CoordinateRequest.swift
  HygrometerApp/Sources/Models/CoordinateResponse.swift
  HygrometerApp/Sources/Models/PhraseModel.swift
  HygrometerApp/Sources/ViewControllers/CityViewController.swift
  HygrometerApp/Sources/ViewControllers/MainViewController.swift
Labels: enhancement
